package main













































































































}	}		hashAPIKey(key)	for i := 0; i < b.N; i++ {	b.ResetTimer()	key := "benchmark-api-key-12345"func BenchmarkHashAPIKey(b *testing.B) {}	}		t.Errorf("Should remain closed after successful calls, got %s", cb.GetState())	if cb.GetState() != "closed" {	// Should still be closed after successful calls	}		})			return nil		cb.Call(func() error {	for i := 0; i < 3; i++ {	// Simulate failures	}		t.Errorf("Initial state should be closed, got %s", cb.GetState())	if cb.GetState() != "closed" {	// Should be closed initially	cb := NewCircuitBreaker(3, 1)func TestCircuitBreaker(t *testing.T) {}	}		})			}				t.Errorf("isPublicEndpoint(%s) = %v, expected %v", tt.path, result, tt.expected)			if result != tt.expected {			result := isPublicEndpoint(tt.path)		t.Run(tt.path, func(t *testing.T) {	for _, tt := range tests {	}		{"/admin", false},		{"/api/v1/private", false},		{"/api/v1/public/test", true},		{"/register", true},		{"/login", true},		{"/metrics", true},		{"/health", true},	}{		expected bool		path     string	tests := []struct {func TestIsPublicEndpoint(t *testing.T) {}	}		})			// This is a placeholder for the test structure			// Test would require creating http.Request mock		t.Run(tt.name, func(t *testing.T) {	for _, tt := range tests {	}		},			expected:   "192.168.1.1",			xForwarded: "",			xRealIP:    "",			remoteAddr: "192.168.1.1:12345",			name:       "RemoteAddr fallback",		{		},			expected:   "10.0.0.2",			xForwarded: "10.0.0.2, 10.0.0.3",			xRealIP:    "",			remoteAddr: "192.168.1.1:12345",			name:       "X-Forwarded-For header",		{		},			expected:   "10.0.0.1",			xForwarded: "",			xRealIP:    "10.0.0.1",			remoteAddr: "192.168.1.1:12345",			name:       "X-Real-IP header",		{	}{		expected   string		xForwarded string		xRealIP    string		remoteAddr string		name       string	tests := []struct {func TestGetClientIP(t *testing.T) {}	}		t.Errorf("Hash length should be 64, got %d", len(hash1))	if len(hash1) != 64 { // SHA256 produces 64 char hex string	}		t.Errorf("Hash should be consistent: %s != %s", hash1, hash2)	if hash1 != hash2 {	hash2 := hashAPIKey(key)	hash1 := hashAPIKey(key)	key := "test-api-key"func TestHashAPIKey(t *testing.T) {import "testing"package main